### ISSUE TITLE
How to use it as a feature extractor

### ISSUE THREAD

**Issue by jgmontoya** [rwightman/gen-efficientnet-pytorch#13]
Hi, 

Is it possible to use this `efficientnet` implementation as a feature extractor? If so how should it be done?

Thanks in advance

**Comment by jgmontoya** [comment]
I resorted to doing this:

```python
model = geffnet.efficientnet_b0(pretrained=True)
feature_extractor = torch.nn.Sequential(*list(model.children())[:-1])
torch.save(feature_extractor, 'efficientnet_b0_fe.pth.tar')
```

And then:

```python
model = torch.load(model_path)
model.eval()
model(image_tensor)[0, :, 0, 0]
```

Do you think is a reasonable approach?

**Comment by rwightman** [comment]
@jgmontoya .... oh, yeah, if you just want the features prior to the linear, yeah, something like that will work, I assumed you were thinking about features at different resolutions for segmentation, etc.

You can do `geffnet.efficientnet_b0(pretrained=True, as_sequential=True)[:-2]` to have the flattened output before linear/droput, `[:-1]` to include dropout,  [:-4] if you want to retain the last spatial feature map (before global pooling and flatten).

**Comment by jgmontoya** [comment]
I'm all for having a more solid feature extractor! Thanks a lot for your work :grin:

**Comment by gaceladri** [comment]
I came here from Pytorch-image-models looking for how to extract features from effnet, also. I am trying to apply "as_sequential" on timm.models.efficientnet_b2(pretrained=True, as_sequential=True) but I am getting the error from the class.
`TypeError: __init__() got an unexpected keyword argument 'as_sequential'`

I know that is not the place but could you elaborate a bit how I can extract the features from the `timm.create_model('efficientnet_b2a', pretrained=use_pretrained)` ?

Thanks!

**Comment by rwightman** [comment]
@gaceladri I didn't add the argument to the factory method in `timm`, `effdet` was being used more by fastai projects so that's why it was added there, wasn't clear anyone wanted that feature in timm. However, the EfficientNet models in both locations have .as_sequential() method that you can call after you create the model.

So, you can
`m = timm.create_model('efficientnet_b2a', pretrained=use_pretrained).as_sequential()` 

Another feature in `timm`, for all models you can just do `model.forward_features(input)` and you'll get an unpooled feature output. In the future it'll be possible to create any model with num_classes=0 or call `.reset(0)` on the model after creating and get pooled featured outputs by default from the normal forward() method.
