### ISSUE TITLE
Unable to create models with current pip release (0.9.8)

### ISSUE THREAD

**Issue by Kshitij09** [rwightman/gen-efficientnet-pytorch#44]
The model creation fails with current PyPI release of this library (**0.9.8**).  

When installed from the sources
```
pip install git+https://github.com/rwightman/gen-efficientnet-pytorch.git
```
There isn't any error and model is being instantiated properly. Seems like some fixes are not yet published to PyPI

**Comment by Kshitij09** [comment]
@rwightman could you confirm this issue?

**Comment by rwightman** [comment]
@Kshitij09  I can't confirm because you didn't actually specify which models. If it's the enhanced mobilenetv2 then yes, it looks like I didn't update pip with those despite prepping the version number. git+ works as you noted, i'll get to this in a week or so when I have another related weight to update.

**Comment by Kshitij09** [comment]
@rwightman Yes, I was working around enhanced mobilenet-v2 which caused this issue but I believe I had also tried the `efficientnet_b3`.

**Comment by rwightman** [comment]
pypi update
