### ISSUE TITLE
I think tf_efficientnet was not trained.

### ISSUE THREAD

**Issue by hjlee9182** [rwightman/gen-efficientnet-pytorch#54]
I tested tf_efficientnet accuracy with ImageNet 2012 _VAL.

And that is result
b0 = 0.699
b1 = 0.717
b2 = 0.721
b3 = 0.724
b4 = 0.717
b5 = 0.619
b6 = 0.694
b7 = 0.523

Why b4~b7 was get lower accuracy than b0~b3?
I think that weight has problem.
Can you check that's weight?

**Comment by rwightman** [comment]
they've all been tested, you're using it wrong, you need to set the correct crop / image interpolation / mean / std / resolution ... it's not automatic because these models are a minimalist version ... if you want models with extra metadata and a validation script that sets those for you, use https://github.com/rwightman/pytorch-image-models
